baseURL = "https://yu-sui.github.io/"
languageCode = "en-us"
title = "Yu Sui | Engineering Notes"
theme = "hugo-paper"

pagination.pagerSize = 10

[params]
color = "linen"   # linen / wheat / gray / light

# home page profile
avatar = "http://localhost:1313/profile.jpg"
name = "Yu Sui"
bio = "Software / Hardware Co-design · FPGA Systems · LLM Inference Infrastructure"

github = "yu-sui"
rss = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2